ARG VERSION=3.4

FROM grafana/loki:${VERSION}

# Copy the loki.yml configuration file to the container
COPY loki.yml /etc/loki/loki-config.yaml

# Command to run Loki with OTLP enabled via flags to bypass YAML parsing issues
CMD ["-config.file=/etc/loki/loki-config.yaml", "-config.expand-env=true"]